"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
from datetime import timedelta
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'se13m4407-2o#mt6ogl5ht$8d9_9bigm3tsyo3eq@n#^9_pmmr'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ['localhost',
                 '0.0.0.0',
                 '192.168.179.104',
                 '192.168.114.104',
                 '192.168.8.38',
                 '192.168.146.104',
                 '192.168.1.37',
                 '127.0.0.1',
                 '192.168.8.47'
                 ]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    "authentication",
    'apps.home',
    "apps.users",
    'doctors',
    "apps.doctor",
    "apps.patients",
    "apps.emails",
    "apps.posts",
    "apps.diagnosis",
    "apps.advertisements",
    'apps.diseases',
    'apps.evaluations',
    'apps.chat',
    'apps.consultations',
    'apps.researches',    
    'notifications',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'eyescare_db',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated', 
    ),
}
CSRF_COOKIE_SECURE = False
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=93),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'TOKEN_BLACKLIST': True,
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'ALGORITHM': 'HS256',
    'TOKEN_TYPE_CLAIM': 'token_type',
}

AUTH_USER_MODEL = 'users.CustomUser'
# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

DJANGO_NOTIFICATIONS_CONFIG = {
    'USE_JSONFIELD': True
    }

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Aden'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "src" / "assets",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ضبط مجلد media
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

GOOGLE_CLIENT_ID='87587319555-i5cute4uqqidlsoia8q6stljaodgtmko.apps.googleusercontent.com'
GOOGLE_CLIENT_SECRET='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'

LOGIN_URL = 'login'
# اعدادات الايميل
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # محرك البريد الإلكتروني
EMAIL_HOST = 'smtp.gmail.com'  # خادم البريد الإلكتروني (SMTP) لـ Gmail
EMAIL_PORT = 587  # رقم المنفذ لـ SMTP مع استخدام TLS
EMAIL_USE_TLS = True  # تمكين TLS (أمان طبقة النقل)
EMAIL_HOST_USER = 'zayedalshuaiby@gmail.com'  # عنوان بريدك الإلكتروني
EMAIL_HOST_PASSWORD = 'nykcqzciwgptybhf'  # كلمة مرور بريدك الإلكتروني
# EMAIL_HOST_USER = 'eyescareapp@gmail.com'  # عنوان بريدك الإلكتروني
# EMAIL_HOST_PASSWORD = 'eyescareapp846#'  # كلمة مرور بريدك الإلكتروني
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER  # عنوان البريد الإلكتروني الافتراضي للمرسل
#  hostpassword:-- Jdv8&:BTW4(=siR
# databasepassword : $finaly6project4
# اعدادات رسائل SMS

# TWILIO_ACCOUNT_SID = 'AC1636dfaebe8c3ac7481c6e9b95958771'
# TWILIO_AUTH_TOKEN = 'a3bb41ecd81533794d2fe9c06cd3ec06'
# TWILIO_PHONE_NUMBER = '+967774656846'


# Pusher API credentials
PUSHER_APP_ID = '1861904'         
PUSHER_KEY = '6c5bc3a240a5017e7aac'              
PUSHER_SECRET = '3c8d562b800fbe10857e'         
PUSHER_CLUSTER = 'ap1'       
PUSHER_SSL = True   

# One Signal Notifications API
ONESIGNAL_APP_ID = "b172908d-fe88-46b7-82b9-3c01efa4e992"
ONESIGNAL_API_KEY = 'YTkwOGJkOTctOTA0NS00ZTMyLTg0ZjctM2VlOGJiNjFjNGUy'

#اعدادات الموديل
ROBOFLOW_API_KEY = 'ItXgPAZWt0DYyYfbUnic'  
ROBOFLOW_API_KEY_For_Detection="BNMaKnfVi9xtFUFmcOFY"
