# Generated by Django 5.0.2 on 2024-08-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='about',
            field=models.CharField(default=1, max_length=800),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.IntegerField(max_length=1),
        ),
    ]
