# Generated by Django 5.0.2 on 2024-08-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_advertisement_about_alter_advertisement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='allowed',
            field=models.BooleanField(default=True),
        ),
    ]
