# Generated by Django 5.0.2 on 2024-09-02 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0004_alter_advertisement_ad_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='user',
        ),
    ]
