# Generated by Django 5.0.2 on 2024-09-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0005_remove_advertisement_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.IntegerField(default=1, max_length=1),
        ),
    ]
