# Generated by Django 5.0.2 on 2024-09-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0006_alter_advertisement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='ad_link',
            field=models.CharField(max_length=200),
        ),
    ]
