# Generated by Django 5.0.2 on 2024-09-03 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0007_alter_advertisement_ad_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
