# Generated by Django 5.0.6 on 2024-10-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertisements", "0008_alter_advertisement_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="allowed",
            field=models.BooleanField(default=False),
        ),
    ]
