# Generated by Django 5.0.6 on 2024-10-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_remove_subscriptionplan_duration_in_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsubscription',
            name='remaining_consultations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='consultation_count',
            field=models.IntegerField(default=0),
        ),
    ]
