# Generated by Django 5.0.6 on 2024-08-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Qualification',
        ),
    ]
