# Generated by Django 5.0.2 on 2024-09-04 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0002_mymodel'),
        ('diseases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisreport',
            name='compeleted',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diagnosisreport',
            name='disease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diseases.disease'),
        ),
    ]
