# Generated by Django 5.0.2 on 2024-09-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0003_diagnosisreport_compeleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosisreport',
            name='diagnosis_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
