# Generated by Django 5.0.6 on 2024-09-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0005_alter_mymodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='image',
            field=models.ImageField(upload_to='images_try/'),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
