# Generated by Django 5.0.6 on 2024-10-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0007_alter_diagnosisreport_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisreport',
            name='confidence',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
