# Generated by Django 5.0.6 on 2024-08-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Patient', 'مريض'), ('Doctor', 'طبيب'), ('Regular', 'مستخدم عادي'), ('Admin', 'ادمن'), ('Support', 'فريق الدعم')], max_length=20),
        ),
    ]
