# Generated by Django 5.0.6 on 2024-08-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_gender_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('ذكر', 'ذكر'), ('أنثى', 'أنثى')], max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('مريض', 'مريض'), ('طبيب', 'طبيب'), ('مستخدم عادي', 'مستخدم عادي'), ('ادمن', 'ادمن'), ('فريق الدعم', 'فريق الدعم')], max_length=20),
        ),
    ]
