# Generated by Django 5.0.6 on 2024-08-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_gender_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('patient', 'مريض'), ('doctor', 'طبيب'), ('user', 'مستخدم عادي'), ('admin', 'ادمن'), ('support', 'فريق الدعم')], max_length=20),
        ),
    ]
