# Generated by Django 5.0.6 on 2024-10-21 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='اليمن', max_length=100)),
                ('governorate', models.CharField(choices=[('أبين', 'أبين'), ('عدن', 'عدن'), ('البيضاء', 'البيضاء'), ('الضالع', 'الضالع'), ('الحديدة', 'الحديدة'), ('الجوف', 'الجوف'), ('المهرة', 'المهرة'), ('المحويت', 'المحويت'), ('عمران', 'عمران'), ('ذمار', 'ذمار'), ('حضرموت', 'حضرموت'), ('حجة', 'حجة'), ('إب', 'إب'), ('لحج', 'لحج'), ('مأرب', 'مأرب'), ('ريمة', 'ريمة'), ('صعدة', 'صعدة'), ('صنعاء', 'صنعاء'), ('شبوة', 'شبوة'), ('سقطرى', 'سقطرى'), ('تعز', 'تعز')], max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
