# Generated by Django 5.0.6 on 2024-10-22 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.date(2007, 1, 1), null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('ذكر', 'ذكر'), ('أنثى', 'أنثى')], default='ذكر', max_length=10),
        ),
    ]
