# Generated by Django 5.0.6 on 2024-09-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='research',
            name='file',
            field=models.FileField(default=2, upload_to='research/'),
            preserve_default=False,
        ),
    ]
