# Generated by Django 5.0.6 on 2024-09-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researches', '0002_remove_research_pdf_file_research_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='abbreviation',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='logo',
            field=models.ImageField(default=2, upload_to='journals_logo/'),
            preserve_default=False,
        ),
    ]
