# Generated by Django 5.0.6 on 2024-09-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researches', '0003_field_description_journal_abbreviation_journal_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='is_file',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='research',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
