# Generated by Django 5.0.6 on 2024-09-29 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researches', '0004_research_is_file_research_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='file',
            field=models.FileField(null=True, upload_to='research/'),
        ),
    ]
