# Generated by Django 5.0.6 on 2024-09-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researches', '0005_alter_research_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='research_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='journal',
            name='research_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
