# Generated by Django 5.0.6 on 2024-09-11 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_received',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='chat_file')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='chat.message')),
            ],
        ),
    ]
