# Generated by Django 5.0.6 on 2024-09-28 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_conversation_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message_file', to='chat.message'),
        ),
    ]
