# Generated by Django 5.0.6 on 2024-10-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor_about_delete_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='end_time_work',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='start_time_work',
            field=models.TimeField(null=True),
        ),
    ]
