# Generated by Django 5.0.6 on 2024-10-21 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
