# Generated by Django 5.0.6 on 2024-10-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0005_delete_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="verification",
            field=models.BooleanField(default=False),
        ),
    ]
