# Generated by Django 5.0.2 on 2024-05-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='اسم الطبيب', max_length=150)),
                ('phone', models.IntegerField()),
                ('profile', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=250)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
