# Generated by Django 5.0.2 on 2024-06-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctors_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctors'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
