# Generated by Django 5.0.6 on 2024-08-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctors_photo_alter_doctors_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/'),
        ),
    ]
