# Generated by Django 5.0.6 on 2024-08-13 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='diseases_images/')),
                ('causes', models.TextField()),
                ('symptoms', models.TextField()),
                ('diagnosis_methods', models.TextField()),
                ('treatment_options', models.TextField()),
                ('prevention_recommendations', models.TextField()),
            ],
        ),
    ]
