# Generated by Django 5.0.6 on 2024-09-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0003_rename_causes_disease_causes_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='causes_ar',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='disease',
            name='causes_en',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='diagnosis_methods_ar',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='disease',
            name='diagnosis_methods_en',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='prevention_recommendations_ar',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='disease',
            name='prevention_recommendations_en',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='symptoms_ar',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='disease',
            name='symptoms_en',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='treatment_options_ar',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='disease',
            name='treatment_options_en',
            field=models.JSONField(null=True),
        ),
    ]
