# Generated by Django 5.0.6 on 2024-10-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0007_alter_disease_causes_ar_alter_disease_causes_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='causes_ar',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='disease',
            name='causes_en',
            field=models.JSONField(null=True),
        ),
    ]
