# Generated by Django 5.0.6 on 2024-10-13 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0008_alter_disease_causes_ar_alter_disease_causes_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='causes_ar',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='diagnosis_methods_ar',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='prevention_recommendations_ar',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='symptoms_ar',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='treatment_options_ar',
        ),
        migrations.AddField(
            model_name='disease',
            name='causes_paragraph_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='causes_points_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='diagnosis_methods_paragraph_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='diagnosis_methods_points_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='prevention_recommendations_paragraph_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='prevention_recommendations_points_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='symptoms_paragraph_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='symptoms_points_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='treatment_options_paragraph_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='treatment_options_points_ar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
