# Generated by Django 5.0.6 on 2024-10-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diseases", "0009_remove_disease_causes_ar_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="disease",
            name="causes_en",
        ),
        migrations.RemoveField(
            model_name="disease",
            name="diagnosis_methods_en",
        ),
        migrations.RemoveField(
            model_name="disease",
            name="prevention_recommendations_en",
        ),
        migrations.RemoveField(
            model_name="disease",
            name="symptoms_en",
        ),
        migrations.RemoveField(
            model_name="disease",
            name="treatment_options_en",
        ),
        migrations.AddField(
            model_name="disease",
            name="causes_paragraph_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="disease",
            name="causes_points_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="disease",
            name="diagnosis_methods_paragraph_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="disease",
            name="diagnosis_methods_points_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="disease",
            name="prevention_recommendations_paragraph_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="disease",
            name="prevention_recommendations_points_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="disease",
            name="symptoms_paragraph_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="disease",
            name="symptoms_points_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="disease",
            name="treatment_options_paragraph_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="disease",
            name="treatment_options_points_en",
            field=models.TextField(blank=True, null=True),
        ),
    ]
